Repository subvisual/discoveryDAO, pull requests merged in 2022-04, with the labels that each got.

#93 Add Sale buy flow
  package.json
  packages/web/README.md
  packages/web/package.json
  packages/web/src/components/connect/terms-and-privacy-link.tsx
  packages/web/src/components/core/button.tsx
  packages/web/src/components/core/form/input-field.tsx
  packages/web/src/components/core/form/styles.ts
  packages/web/src/components/core/link.tsx
  packages/web/src/components/core/modal.tsx
  packages/web/src/components/core/text.tsx
  packages/web/src/components/dashboard/error-modal.tsx
  packages/web/src/components/dashboard/project-info-card.tsx
  packages/web/src/components/dashboard/sale-confirming-modal.tsx
  packages/web/src/components/dashboard/sale-form.tsx
  packages/web/src/components/navbar.tsx
  packages/web/src/components/page-content.tsx
  packages/web/src/components/screens/dashboard.tsx
  packages/web/src/context/contracts.tsx
  packages/web/src/hooks/use-owner-action.ts
  packages/web/src/hooks/use-sale.ts
  yarn.lock
Labels: large

#96 Update Navbar menu styles
  packages/web/README.md
  packages/web/src/assets/svgs/check.svg
  packages/web/src/assets/svgs/error.svg
  packages/web/src/assets/svgs/hexagon-stroked.svg
  packages/web/src/components/core/separator.tsx
  packages/web/src/components/dashboard/project-info-card.tsx
  packages/web/src/components/navbar.tsx
  packages/web/src/components/page-content.tsx
  packages/web/src/components/screens/connect.tsx
  packages/web/src/components/screens/dashboard.tsx
  packages/web/src/core/utils/formatters.ts
  packages/web/src/pages/_document.tsx
Labels: medium

#98 Add Vesting countdown
  packages/web/package.json
  packages/web/src/components/core/card.tsx
  packages/web/src/components/countdown.tsx
  packages/web/src/components/screens/dashboard.tsx
  packages/web/src/styles/global.ts
  yarn.lock
Labels: medium

#92 Basic checks to invest in the project pools
  packages/contracts/contracts/discovery/Batch.sol
  packages/contracts/contracts/discovery/Controller.sol
  packages/contracts/contracts/discovery/Staking.sol
  packages/contracts/contracts/discovery/interfaces/IController.sol
  packages/contracts/contracts/discovery/interfaces/IStaking.sol
  packages/contracts/deploy/controller.ts
  packages/contracts/test/contracts/discovery/Controller.ts
Labels: large

#104 Add vesting flow
  packages/web/src/assets/svgs/error-info.svg
  packages/web/src/components/core/form/input-field.tsx
  packages/web/src/components/core/form/styles.ts
  packages/web/src/components/core/form/styles.tsx
  packages/web/src/components/countdown.tsx
  packages/web/src/components/dashboard/sale-form.tsx
  packages/web/src/components/navbar.tsx
  packages/web/src/components/screens/dashboard.tsx
  packages/web/src/components/vesting/index.tsx
  packages/web/src/components/vesting/info-card.tsx
  packages/web/src/components/vesting/loading-modal.tsx
  packages/web/src/components/vesting/styles.tsx
  packages/web/src/core/utils/formatters.ts
  packages/web/src/hooks/use-app-status.ts
  packages/web/src/hooks/use-vesting.ts
  packages/web/src/styles/global.ts
Labels: large

#107 Add signature request
  packages/web/package.json
  packages/web/src/components/connect/modal-wallet-connect.tsx
  packages/web/src/components/core/modal.tsx
  packages/web/src/components/dashboard/error-modal.tsx
  packages/web/src/components/dashboard/sale-form.tsx
  packages/web/src/components/navbar.tsx
  packages/web/src/components/page-content.tsx
  packages/web/src/components/screens/connect.tsx
  packages/web/src/components/screens/dashboard.tsx
  packages/web/src/components/signature/awaiting-signature-modal.tsx
  packages/web/src/context/session.tsx
  packages/web/src/core/utils/web3-api-handlers.tsx
  packages/web/src/core/utils/web3-signature.ts
  packages/web/src/hooks/use-kyc-status.ts
  packages/web/src/hooks/use-sale.ts
  packages/web/src/hooks/use-vesting.ts
  packages/web/src/hooks/use-wallet-connect.ts
  packages/web/src/pages/_app.tsx
  packages/web/src/pages/admin.tsx
  packages/web/src/pages/index.tsx
  packages/web/src/styles/global.ts
  yarn.lock
Labels: medium, large

#116 Deploying to mandala, and publishing contracts
  packages/contracts/deployments/mandala/Citizend.json
  packages/contracts/deployments/mandala/EVM.json
  packages/contracts/deployments/mandala/FractalRegistry.json
  packages/contracts/deployments/mandala/Sale1.json
  packages/contracts/deployments/mandala/Vesting.json
  packages/contracts/deployments/mandala/solcInputs/48c0395a6d789fc766b365a100c4e3fd.json
  packages/contracts/src/acala/index.ts
Labels: large

#117 Trying out new values for revy.yml PR sizes
  revy.yml
Labels: small
