Repository subvisual/discoveryDAO, pull requests merged in 2022-05, with the labels that each got.

#119 Add wrong network selected modal
  packages/web/README.md
  packages/web/src/components/modals/wrong-chain-modal.tsx
  packages/web/src/components/screens/connect.tsx
  packages/web/src/core/utils/web3-connectors.ts
  packages/web/src/hooks/use-referral-url.ts
Labels: medium

#110 Add favicons
  packages/web/public/browserconfig.xml
  packages/web/public/favicon.ico
  packages/web/public/favicon/android-icon-192x192.png
  packages/web/public/favicon/apple-icon-114x114.png
  packages/web/public/favicon/apple-icon-120x120.png
  packages/web/public/favicon/apple-icon-144x144.png
  packages/web/public/favicon/apple-icon-152x152.png
  packages/web/public/favicon/apple-icon-180x180.png
  packages/web/public/favicon/apple-icon-57x57.png
  packages/web/public/favicon/apple-icon-60x60.png
  packages/web/public/favicon/apple-icon-72x72.png
  packages/web/public/favicon/apple-icon-76x76.png
  packages/web/public/favicon/favicon-16x16.png
  packages/web/public/favicon/favicon-256x256.png
  packages/web/public/favicon/favicon-32x32.png
  packages/web/public/favicon/favicon-96x96.png
  packages/web/public/favicon/ms-icon-144x144.png
  packages/web/public/favicon/ms-icon-150x150.png
  packages/web/public/favicon/ms-icon-310x310.png
  packages/web/public/favicon/ms-icon-70x70.png
  packages/web/public/manifest.json
  packages/web/src/pages/_document.tsx
Labels: small

#120 Fix Tokens release date for first of next month
  packages/web/src/components/vesting/index.tsx
  packages/web/src/components/vesting/info-card.tsx
  packages/web/src/core/utils/formatters.ts
Labels: small

#109 Improvements to Batch and Controller communication
  packages/contracts/contracts/discovery/Batch.sol
  packages/contracts/contracts/discovery/Controller.sol
  packages/contracts/contracts/discovery/TestProjectVoting.sol
  packages/contracts/contracts/discovery/interfaces/IController.sol
  packages/contracts/test/contracts/discovery/Batch.ts
  packages/contracts/test/contracts/discovery/Controller.ts
  packages/contracts/test/contracts/discovery/helpers.ts
Labels: large

#121 Fix network select modal not appearing
  packages/web/src/components/screens/connect.tsx
  packages/web/src/core/utils/web3-connectors.ts
  packages/web/src/pages/_app.tsx
Labels: bug, small

#123 Deploy #3
  packages/contracts/deployments/mandala/Citizend.json
  packages/contracts/deployments/mandala/FractalRegistry.json
  packages/contracts/deployments/mandala/Sale1.json
  packages/contracts/deployments/mandala/Vesting.json
  packages/contracts/deployments/mandala/solcInputs/decdec93551b6311883ac2259c1f6c65.json
  packages/contracts/src/deployConfigs.ts
Labels: medium

#122 Fix Share modal without scroll for small screens
  packages/web/src/components/core/modal.tsx
  packages/web/src/styles/global.ts
Labels: small

#131 Temporarily skipping a couple of tests
  packages/contracts/test/tasks/ctnd/risingTide.ts
Labels: small

#130 FIX USD values and cards not showing properly
  packages/web/README.md
  packages/web/src/components/countdown.tsx
  packages/web/src/components/dashboard/project-info-card.tsx
  packages/web/src/components/dashboard/sale-form.tsx
  packages/web/src/components/modals/share-referral-modal.tsx
  packages/web/src/components/navbar.tsx
  packages/web/src/components/screens/dashboard.tsx
  packages/web/src/components/vesting/index.tsx
  packages/web/src/core/constants.ts
  packages/web/src/core/utils/formatters.ts
  packages/web/src/core/utils/web3-api-handlers.tsx
  packages/web/src/hooks/use-owner-action.ts
Labels: small

#132 Fixing rising tide tests
  packages/contracts/test/tasks/ctnd/risingTide.ts
Labels: small

#135 Adding hacken's audit report
  README.md
  audits/2022-05-04_hacken_token-sale.pdf
Labels: small

#138 Improving kyc whitelist script (for testing purposes)
  packages/contracts/scripts/mandalaKyc.ts
  packages/contracts/scripts/test.kycWhitelist.ts
Labels: small

#137 Fixing decimal places
  packages/web/src/hooks/use-sale.ts
Labels: small

#139 Vesting updates based on feedback
  packages/contracts/contracts/token/IVesting.sol
  packages/contracts/contracts/token/Vesting.sol
  packages/contracts/deploy/ctnd/vesting.deploy.ts
  packages/contracts/src/tasks/ctnd/privateSale.ts
  packages/contracts/test/contracts/token/Vesting.ts
  packages/contracts/test/integration/ctnd.sale.ts
Labels: small

#140 Require full KYC to invest
  packages/contracts/contracts/token/Sale.sol
  packages/contracts/scripts/test.kycWhitelist.ts
  packages/contracts/test/contracts/token/Sale.ts
  packages/contracts/test/integration/ctnd.sale.ts
  packages/contracts/test/tasks/ctnd/risingTide.ts
  packages/web/src/hooks/use-owner-action.ts
Labels: small

#146 Submits rising tide calculation to sale contract
  packages/contracts/src/acala/index.ts
  packages/contracts/src/tasks/ctnd/risingTide.ts
  packages/contracts/test/tasks/ctnd/risingTide.ts
Labels: small

#134 Adds correct fractal root wallet for mandala
  packages/contracts/contracts/fractal_registry/FractalRegistry.sol
  packages/contracts/deploy/ctnd/sale1.deploy.ts
  packages/contracts/deploy/fractalRegistry.ts
  packages/contracts/deploy/registry/registry.addDelegate.ts
  packages/contracts/deploy/registry/registry.deploy.ts
  packages/contracts/src/deployConfigs.ts
Labels: small

#112 Adds total vote limit per user for batch
  packages/contracts/contracts/discovery/Batch.sol
  packages/contracts/contracts/discovery/ProjectVoting.sol
  packages/contracts/contracts/discovery/TestProjectVoting.sol
  packages/contracts/test/contracts/discovery/Batch.ts
  packages/contracts/test/contracts/discovery/ProjectVoting.ts
  packages/contracts/test/contracts/discovery/helpers.ts
Labels: small

#141 Fix timezones mismatch and blockchain data loading
  packages/web/package.json
  packages/web/src/components/dashboard/project-info-card.tsx
  packages/web/src/components/screens/dashboard.tsx
  packages/web/src/components/vesting/index.tsx
  packages/web/src/core/utils/dayjs.ts
  packages/web/src/core/utils/formatters.ts
  packages/web/src/core/utils/web3-connectors.ts
  packages/web/src/hooks/use-app-status.ts
  packages/web/src/hooks/use-sale.ts
  yarn.lock
Labels: medium

#152 Add sale end without vesting date
  packages/web/src/components/dashboard/project-info-card.tsx
  packages/web/src/components/screens/dashboard.tsx
  packages/web/src/components/unknown-date.tsx
  packages/web/src/components/vesting/index.tsx
  packages/web/src/core/constants.ts
  packages/web/src/core/utils/formatters.ts
  packages/web/src/hooks/use-app-status.ts
  packages/web/src/hooks/use-vesting.ts
Labels: enhancement, medium

#150 Ability to run entire dev environment with a single command
  package.json
  packages/contracts/scripts/test.setVestingStart.ts
  packages/dev/.eslintrc.js
  packages/dev/.gitignore
  packages/dev/.prettierignore
  packages/dev/.prettierrc
  packages/dev/index.ts
  packages/dev/package.json
  packages/dev/tsconfig.json
  packages/dev/yarn.lock
  packages/web/wait-for-node.sh
  yarn.lock
Labels: large

#154 Final fixes to make testing smoother
  packages/contracts/deploy/ctnd/vesting.deploy.ts
  packages/contracts/deploy/ctnd/vesting.test.setStart.ts
  packages/contracts/deploy/registry/registry.test.delegate.ts
  packages/contracts/deploy/registry/registry.test.whitelist.ts
  packages/contracts/scripts/test.kycWhitelist.ts
  packages/contracts/scripts/test.setVestingStart.ts
  packages/contracts/src/deployConfigs.ts
  packages/contracts/src/tasks/ctnd/risingTide.ts
  packages/contracts/test/integration/ctnd.sale.ts
  packages/dev/package.json
  packages/web/src/hooks/use-vesting.ts
Labels: medium

#158 Show 0 to be refunded after refund
  packages/contracts/contracts/token/Sale.sol
  packages/contracts/test/contracts/token/Sale.ts
Labels: small

#160 Fixing deploy publish step
  packages/contracts/src/acala/index.ts
Labels: small

#161 Clear sale form on submit
  packages/web/src/components/dashboard/sale-form.tsx
Labels: small

#162 Add Metamask new token handling mechanism
  packages/web/src/components/core/link.tsx
  packages/web/src/components/dashboard/project-info-card.tsx
  packages/web/src/components/dashboard/sale-form.tsx
  packages/web/src/components/screens/connect.tsx
  packages/web/src/components/vesting/index.tsx
  packages/web/src/components/vesting/info-card.tsx
  packages/web/src/components/vesting/styles.tsx
  packages/web/src/hooks/use-vesting.ts
  packages/web/src/types/global.d.ts
Labels: medium

#164 Update Vesting to allow refund on countdown state
  packages/web/src/components/screens/dashboard.tsx
  packages/web/src/components/vesting/index.tsx
  packages/web/src/hooks/use-app-status.ts
Labels: small
